# Generated by Django 4.2.5 on 2023-10-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Image", models.ImageField(upload_to="media/Slider_img")),
                (
                    "Discount_Deals",
                    models.CharField(
                        choices=[
                            ("HOT DEALS", "HOT DEALS"),
                            ("NEW ARRIVAL", "NEW ARRIVAL"),
                            ("NEW DEALS", "NEW DEALS"),
                        ],
                        max_length=100,
                    ),
                ),
                ("Sale", models.IntegerField()),
                ("Brand_Name", models.CharField(max_length=100)),
                ("Discount", models.IntegerField()),
                ("Link", models.CharField(max_length=200)),
            ],
        ),
    ]
